---
- name: Ensure ViM exists 
  yum:
    name: "vim"
    state: present
  when: ansible_distribution_major_version <= "7"

- name: Ensure ViM exists 
  dnf:
    name: "vim"
    state: present
  when: ansible_distribution_major_version > "7"